name: Create draft branch

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Create draft branch
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      # Run draft script
      - run: bash scripts/draft.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}